name: flutter_demo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  retrofit: ^1.3.4+1
  url_launcher: ^5.7.10
  timeago: ^2.0.30
  carousel_slider: ^3.0.0
  eva_icons_flutter: ^2.0.1
  flutter_html: ^1.2.0
  protobuf: <=0.13.15
  provider: ^4.3.3
  stripe_payment: ^1.0.10
#  dio: ^3.0.9
  json_serializable: ^3.5.1
  #retrofit: any
  logger: any
  flutter_icons: ^1.1.0
  connectivity: ^2.0.2
  qr_code_scanner: ^0.3.5
  intl: ^0.16.0
  firebase_dynamic_links: ^0.7.0
  firebase_core: ^0.7.0
  firebase_analytics: any
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^4.0.1

flutter_icons:
  image_path: 'assets/logo_app/mobileapp.png'
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/logo_app/mobileapp.png
     - assets/json/jsondepartment.json
     - assets/json/json.json
     - assets/json/orderdetails.json
     - assets/img/placeholder.png
     - assets/logos/abc-news.png
     - assets/logos/ars-technica.png
     - assets/logos/associated-press.png
     - assets/logos/axios.png
     - assets/logos/bbc-news.png
     - assets/logos/bbc-sport.png
     - assets/logos/bleacher-report.png
     - assets/logos/bloomberg.png
     - assets/logos/business-insider.png
     - assets/logos/buzzfeed.png
     - assets/logos/cbc-news.png
     - assets/logos/cbs-news.png
     - assets/logos/cnn.png
     - assets/logos/espn.png
     - assets/logos/financial-post.png
     - assets/logos/fortune.png
     - assets/logos/fox-news.png
     - assets/logos/fox-sports.png
     - assets/logos/google-news.png
     - assets/logos/hacker-news.png
     - assets/logos/ign.png
     - assets/logos/independent.png
     - assets/logos/mashable.png
     - assets/logos/msnbc.png
     - assets/logos/mtv-news.png
     - assets/logos/national-geographic.png
     - assets/logos/news24.png
     - assets/logos/politico.png
     - assets/logos/recode.png
     - assets/logos/reuters.png
     - assets/logos/rte.png
     - assets/logos/techcrunch.png
     - assets/logos/techradar.png
     - assets/logos/the-hill.png
     - assets/logos/the-huffington-post.png
     - assets/logos/the-next-web.png
     - assets/logos/the-wall-street-journal.png
     - assets/logos/the-washington-post.png
     - assets/logos/time.png
     - assets/logos/wired.png
     - assets/logos/breitbart-news.png
     - assets/logos/crypto-coins-news.png
     - assets/logos/engadget.png
     - assets/logos/entertainment-weekly.png
     - assets/logos/espn-cric-info.png
     - assets/logos/medical-news-today.png
     - assets/logos/national-review.png
     - assets/logos/nbc-news.png
     - assets/logos/new-scientist.png
     - assets/logos/newsweek.png
     - assets/logos/next-big-future.png
     - assets/logos/nfl-news.png
     - assets/logos/nhl-news.png
     - assets/logos/polygon.png
     - assets/logos/reddit-r-all.png
     - assets/logos/new-york-magazine.png
     - assets/logos/the-american-conservative.png
     - assets/logos/the-verge.png
     - assets/logos/the-washington-times.png
     - assets/logos/usa-today.png
     - assets/logos/vice-news.png
     - assets/logos/logo_placeholder.png
     - assets/logos/al-jazeera-english.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
